CREATE TABLE SQLMAP (
  KEY_ VARCHAR(100) PRIMARY KEY,
  sql_ VARCHAR(100) NOT NULL
);

INSERT INTO SQLMAP(KEY_, SQL_) values ('KEY1', 'SQL1');
INSERT INTO SQLMAP(KEY_, SQL_) values ('KEY2', 'SQL2');
INSERT INTO SQLMAP(KEY_, SQL_) values ('KEY3', 'SQL3');